name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod tidy
      - name: Run test with coverage
        run: |
          go test -p 1 -v -coverprofile coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html
      - name: Upload test coverage to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/coverage.html
          name: ${{ runner.os }}-${{ env.BRANCH_NAME }}-coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=TestingOrg993_sonarcloud
            -Dsonar.organization=testingorg993
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.language=go
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.tests=.
            -Dsonar.go.tests.reportPaths=report.json
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
